[package]
name = "comunicacao"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
crossterm = "0.28.1"
interfaces = "0.0.9"
local-ip-address = "0.6.3"
rand = "0.8.5"
ratatui = "0.28.1"
